name: API Build and Push
on:
    push:
        branches:
            - "main"
        paths:
            - api/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./api
                  push: true
                  tags: ghcr.io/${{ github.repository }}/api:latest
