name: API Build and Push
on:
    push:
        branches:
            - "main"
        paths:
            - api/**

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set repo name to lowercase
              id: repo
              run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./api/Dockerfile
                  push: true
                  tags: ghcr.io/${{ steps.repo.outputs.repo }}/api:latest
